// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWcs2KcU2JHSq_6SCl3iwtaKw6MIfbAFc',
    appId: '1:918320702070:web:22236cb29d0fb1d09d3557',
    messagingSenderId: '918320702070',
    projectId: 'isjtouchhealth-app',
    authDomain: 'isjtouchhealth-app.firebaseapp.com',
    storageBucket: 'isjtouchhealth-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0-D8VGUevmyR3nYNIjoGF1ocUnq5TN8',
    appId: '1:918320702070:android:087688d09a3a62759d3557',
    messagingSenderId: '918320702070',
    projectId: 'isjtouchhealth-app',
    storageBucket: 'isjtouchhealth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgwwG4dBIB8DWCltKBcmOnZnRM7dW_Hc8',
    appId: '1:918320702070:ios:7a56afddd0891cbf9d3557',
    messagingSenderId: '918320702070',
    projectId: 'isjtouchhealth-app',
    storageBucket: 'isjtouchhealth-app.firebasestorage.app',
    iosBundleId: 'com.example.touchHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgwwG4dBIB8DWCltKBcmOnZnRM7dW_Hc8',
    appId: '1:918320702070:ios:7a56afddd0891cbf9d3557',
    messagingSenderId: '918320702070',
    projectId: 'isjtouchhealth-app',
    storageBucket: 'isjtouchhealth-app.firebasestorage.app',
    iosBundleId: 'com.example.touchHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWcs2KcU2JHSq_6SCl3iwtaKw6MIfbAFc',
    appId: '1:918320702070:web:09f3621de982482c9d3557',
    messagingSenderId: '918320702070',
    projectId: 'isjtouchhealth-app',
    authDomain: 'isjtouchhealth-app.firebaseapp.com',
    storageBucket: 'isjtouchhealth-app.firebasestorage.app',
  );

}